### ISSUE TITLE
Request: Make the sensor time field of indices uniform

### ISSUE THREAD

**Issue by una-dinosauria** [pit30m/pit30m#22]
Right now, it is called `"img_time"` for cameras, and `"lidar_time"` for lidar. Some of the internal logic would be cleaner if these two fields were simply called `"sensor_time`" or something like that

**Comment by AndreiBarsan** [comment]
@una-dinosauria is this still necessary from your point of view? I assume you already worked around this issue in the partition generation line of work, right?

I think one reason to keep these two names different is because they mean different things - for the camera it's the (global) shutter time, but for LiDAR it's somewhat arbitrary. In my case I store the median timestamp... I may rename the field in future index versions to improve clarity, maybe. What do you think?

**Comment by una-dinosauria** [comment]
> @una-dinosauria is this still necessary from your point of view? I assume you already worked around this issue in the partition generation line of work, right?

Yep, I parameterized everything with a `"time_field"` variables that changes depending on what data we are using.

> I think one reason to keep these two names different is because they mean different things - for the camera it's the (global) shutter time, but for LiDAR it's somewhat arbitrary. In my case I store the median timestamp... I may rename the field in future index versions to improve clarity, maybe. What do you think?

This is a very good argument! I think  we can close this issue then.
